name: ctask
description: "CTask - A modern 4-state todo management app with dark mode, data persistence, and responsive design."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.23.0
  cloud_firestore: ^4.10.0
  firebase_database: ^10.0.6
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
