// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdqSDeVhAYlRaFOUUmozq4SLvz7fxyhU',
    appId: '1:142573738055:web:d58c6f110c05b93007b962',
    messagingSenderId: '142573738055',
    projectId: 'ctask-a7cbb',
    authDomain: 'ctask-a7cbb.firebaseapp.com',
    storageBucket: 'ctask-a7cbb.firebasestorage.app',
    // Realtime Database URL (required by firebase_database)
    databaseURL: 'https://ctask-a7cbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-584LFV98VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUA7hin7p_V4voi5Dgqw2doOlLw-QD9A',
    appId: '1:142573738055:android:071e661477fa2c2807b962',
    messagingSenderId: '142573738055',
    projectId: 'ctask-a7cbb',
    storageBucket: 'ctask-a7cbb.firebasestorage.app',
    databaseURL: 'https://ctask-a7cbb-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZkXrbKystqUAaypcYshPR9VHeTPhHj4',
    appId: '1:142573738055:ios:c0531e188f7dce7407b962',
    messagingSenderId: '142573738055',
    projectId: 'ctask-a7cbb',
    storageBucket: 'ctask-a7cbb.firebasestorage.app',
    databaseURL: 'https://ctask-a7cbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.ctask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZkXrbKystqUAaypcYshPR9VHeTPhHj4',
    appId: '1:142573738055:ios:c0531e188f7dce7407b962',
    messagingSenderId: '142573738055',
    projectId: 'ctask-a7cbb',
    storageBucket: 'ctask-a7cbb.firebasestorage.app',
    databaseURL: 'https://ctask-a7cbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.ctask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCdqSDeVhAYlRaFOUUmozq4SLvz7fxyhU',
    appId: '1:142573738055:web:1aa18cb72d7825ab07b962',
    messagingSenderId: '142573738055',
    projectId: 'ctask-a7cbb',
    authDomain: 'ctask-a7cbb.firebaseapp.com',
    storageBucket: 'ctask-a7cbb.firebasestorage.app',
    databaseURL: 'https://ctask-a7cbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-57L8M8Z0D0',
  );
}
